apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-blue
spec:
  template:
    spec:
      containers:
        - name: my-app
          image: amoghlokhande/myapp:9
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-green
spec:
  template:
    spec:
      containers:
        - name: my-app
          image: amoghlokhande/myapp:9
